# 3-3 numpy.array 基础

### 导入numpy

In [2]:
import numpy

In [3]:
numpy.__version__

'1.14.0'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.14.0'

### python中list的特点

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
L[5]

5

In [9]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [10]:
L[5] = "machine learning"
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

### python中的array

In [11]:
import array

In [13]:
arr = array.array("i", [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [16]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [17]:
arr[5] = "machine learning"
arr

TypeError: an integer is required (got type str)

### numpy.array

In [19]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr[5]

5

In [21]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [22]:
nparr[5] = "machine learning"
nparr

ValueError: invalid literal for int() with base 10: 'machine learning'

In [23]:
nparr.dtype

dtype('int32')

In [24]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
nparr.dtype

dtype('int32')

In [26]:
nparr[5] = 5.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr.dtype

dtype('int32')

In [28]:
nparr[5] = 5.67
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr.dtype

dtype('int32')

In [30]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [31]:
nparr2.dtype

dtype('float64')