In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
L

array([0.74347775, 0.73341021, 0.72030565, 0.48985749, 0.69310915,
       0.61800531, 0.94394877, 0.79332942, 0.16156939, 0.99626732,
       0.45995162, 0.16753547, 0.99215661, 0.18203243, 0.47557483,
       0.57718781, 0.3630272 , 0.75463605, 0.78867924, 0.8367136 ,
       0.0483958 , 0.69476014, 0.32908307, 0.23232765, 0.69667256,
       0.26536745, 0.17513392, 0.72658578, 0.43741452, 0.16317591,
       0.12247231, 0.84214327, 0.63370907, 0.71776698, 0.7449534 ,
       0.57766259, 0.55374816, 0.18464221, 0.07874796, 0.98283442,
       0.57574232, 0.14460336, 0.12572875, 0.77492908, 0.96736151,
       0.13494908, 0.56944173, 0.79454376, 0.20409648, 0.79349396,
       0.88738904, 0.52729874, 0.17316929, 0.1621103 , 0.7566519 ,
       0.04559596, 0.5959264 , 0.36043175, 0.52039314, 0.73243104,
       0.71045134, 0.06338018, 0.7819356 , 0.33381743, 0.90421053,
       0.31427757, 0.60257547, 0.86561982, 0.82069904, 0.85082579,
       0.82952083, 0.20640668, 0.34638602, 0.04776328, 0.70819

In [3]:
sum(L)

52.169496060967774

In [4]:
np.sum(L)

52.16949606096779

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

145 ms ± 6.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.11 ms ± 29.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

8.960951823899777e-07

In [7]:
np.max(big_array)

0.9999964720085904

In [8]:
big_array.min()

8.960951823899777e-07

In [9]:
big_array.max()

0.9999964720085904

In [10]:
big_array.sum()

499661.13236968743

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)

0

In [16]:
X.dtype

dtype('int32')

In [17]:
np.prod(X + 1)

2004189184

In [18]:
np.mean(X)

7.5

In [19]:
np.median(X)

7.5

In [20]:
v = np.array([1, 2, 1, 2, 10])
np.mean(v)

3.2

In [21]:
v.dtype

dtype('int32')

In [22]:
np.median(v)

2.0

In [23]:
np.percentile(big_array, q=50)

0.4997916872646732

In [24]:
np.median(big_array)

0.4997916872646732

In [26]:
np.percentile(big_array, q=100)

0.9999964720085904

In [27]:
np.max(big_array)

0.9999964720085904

In [28]:
np.percentile(big_array, q=0)

8.960951823899777e-07

In [29]:
np.min(big_array)

8.960951823899777e-07

In [32]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

8.960951823899777e-07
0.24943869840481223
0.4997916872646732
0.7493404486545031
0.9999964720085904


In [33]:
np.var(big_array)

0.08332752561485948

In [34]:
np.std(big_array)

0.2886650751560699

In [35]:
x = np.random.normal(0, 1, size=1000000)

In [36]:
np.mean(x)

-0.0002176177827171757

In [37]:
np.var(x)

0.9984852951110059