### 索引

In [2]:
import numpy as np

In [3]:
x = np.random.normal(0, 1, size=1000000)

In [4]:
np.min(x)

-4.808101499068913

In [5]:
np.argmin(x)

938153

In [6]:
x[938153]

-4.808101499068913

In [7]:
np.max(x)

4.850220601825031

In [8]:
np.argmax(x)

363034

In [9]:
x[363034]

4.850220601825031

### 排序和使用索引

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)  ###乱序处理
x

array([ 6,  1, 10,  4,  8,  3, 11,  7,  5, 12, 15, 14,  2,  0,  9, 13])

In [13]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x

array([ 6,  1, 10,  4,  8,  3, 11,  7,  5, 12, 15, 14,  2,  0,  9, 13])

In [15]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X = np.random.randint(10, size=(4, 4))
X

array([[2, 4, 0, 2],
       [8, 3, 4, 1],
       [3, 2, 5, 8],
       [7, 5, 3, 6]])

In [19]:
np.sort(X)

array([[0, 2, 2, 4],
       [1, 3, 4, 8],
       [2, 3, 5, 8],
       [3, 5, 6, 7]])

In [20]:
np.sort(X, axis=1)

array([[0, 2, 2, 4],
       [1, 3, 4, 8],
       [2, 3, 5, 8],
       [3, 5, 6, 7]])

In [21]:
np.sort(X, axis=0)

array([[2, 2, 0, 1],
       [3, 3, 3, 2],
       [7, 4, 4, 6],
       [8, 5, 5, 8]])

In [22]:
X

array([[2, 4, 0, 2],
       [8, 3, 4, 1],
       [3, 2, 5, 8],
       [7, 5, 3, 6]])

In [23]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.random.shuffle(x)

In [25]:
x

array([12,  8,  4, 11,  3,  7,  9,  0,  6,  1, 13, 14, 15,  2, 10,  5])

In [26]:
np.argsort(x)

array([ 7,  9, 13,  4,  2, 15,  8,  5,  1,  6, 14,  3,  0, 10, 11, 12],
      dtype=int64)

In [28]:
np.partition(x, 3)

array([ 2,  1,  0,  3,  4,  5,  9,  8,  6,  7, 13, 14, 15, 11, 10, 12])

In [29]:
np.argpartition(x, 3)

array([13,  9,  7,  4,  2, 15,  6,  1,  8,  5, 10, 11, 12,  3, 14,  0],
      dtype=int64)

In [30]:
x

array([12,  8,  4, 11,  3,  7,  9,  0,  6,  1, 13, 14, 15,  2, 10,  5])

In [31]:
X

array([[2, 4, 0, 2],
       [8, 3, 4, 1],
       [3, 2, 5, 8],
       [7, 5, 3, 6]])

In [32]:
np.partition(X, 2, axis=1)

array([[0, 2, 2, 4],
       [1, 3, 4, 8],
       [2, 3, 5, 8],
       [3, 5, 6, 7]])

In [33]:
np.argpartition(X, 2, axis=1)

array([[2, 0, 3, 1],
       [3, 1, 2, 0],
       [1, 0, 2, 3],
       [2, 1, 3, 0]], dtype=int64)

In [34]:
np.partition(X, 2, axis=0)

array([[2, 2, 0, 1],
       [3, 3, 3, 2],
       [7, 4, 4, 6],
       [8, 5, 5, 8]])

In [35]:
np.argpartition(X, 2, axis=0)

array([[0, 2, 0, 1],
       [2, 1, 3, 0],
       [3, 0, 1, 3],
       [1, 3, 2, 2]], dtype=int64)