In [1]:
import numpy as np

In [2]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [20]:
%run ../myscript/Chapter-4/kNN.py

In [21]:
predict_y = kNN_classify(6, X_train, y_train, x)
predict_y

1

### 使用scikit-learn中的kNN

In [ ]:
#准备X_train, y_train, x
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [7]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [16]:
X_predict = x.reshape(1, -1)
X_predict

array([[8.09360732, 3.36573151]])

In [18]:
kNN_classifier.predict(X_predict)

array([1])

### 我们自己封装类似scikit-learn中的KNeighborsClassifier

In [22]:
#准备X_train, y_train, x
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [23]:
X_predict = x.reshape(1, -1)

In [27]:
%run ../myscript/Chapter-4/kNN2.py

In [28]:
knn_clf = KNNClassifier(k=6)

In [29]:
knn_clf.fit(X_train, y_train)

kNN(k=6)

In [30]:
y_predict = knn_clf.predict(X_predict)
y_predict

array([1])